spring:
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: true

rest:
  endpoint:
    fashion: "http://fashion-bestseller.steadybit.local:8082/products"
    toys: "http://toys-bestseller.steadybit.local:8081/products"
    hotdeals: "http://hot-deals.steadybit.local:8083/products"