name: CVE Scan Main

permissions:
  contents: read
  security-events: write
  packages: read
  id-token: write

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  cve_scan_orders_go:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/orders-go'
      image_tag: 'main'
  cve_scan_checkout_go:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/checkout-go'
      image_tag: 'main'
  cve_scan_inventory_go:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/inventory-go'
      image_tag: 'main'
  cve_scan_bestseller_toys_go:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/bestseller-toys-go'
      image_tag: 'main'
  cve_scan_gateway:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/gateway'
      image_tag: 'main'
  cve_scan_hot_deals:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/hot-deals'
      image_tag: 'main'
  cve_scan_bestseller_fashion:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/bestseller-fashion'
      image_tag: 'main'
  cve_scan_checkout:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/checkout'
      image_tag: 'main'
  cve_scan_inventory:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/inventory'
      image_tag: 'main'
  cve_scan_bestseller_toys:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/bestseller-toys'
      image_tag: 'main'
  cve_scan_orders:
    uses: steadybit/extension-kit/.github/workflows/reusable-cve-scan.yml@main # NOSONAR githubactions:S7637 - our own action
    with:
      image_name: 'steadybit/orders'
      image_tag: 'main'
